name: Run

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # run it manually
  workflow_dispatch:    

jobs:

  build:

    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}  

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        cd ~
        git clone https://github.com/justdan96/7zip_static.git
        cd 7zip_static
        docker build --build-arg VERSION=$(curl -s https://www.7-zip.org/history.txt | head -n 4 | grep -Po '\K[0-9.]{5}+' | tr -d '.') -t 7zip_static .

    - name: build static program with alpine linux docker 
      run: |
        docker run -t --rm -v $(pwd):/workdir -w="/workdir" 7zip_static sh -c "cp /opt/* /workdir"

    - name: "Compression 7zip static program"
      run: | 
        sudo apt update
        sudo apt install --yes lzip    
        cd ~/7zip_static
        tar -I 'lzip -9' -vcf 7zz.tlz ./7zz

    - name: Upload 7zip static program
      uses: actions/upload-artifact@v4
      with:
        name: 7zz-${{ matrix.os }}
        path: ~/7zip_static/7zz.tlz
